version: '3.8'
services:
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  app:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - JWT_SECRET=chatsecret
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
