# Register
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "test",
  "password": "test",
  "profilePicture": "test"
}

###
# Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###
# Get all users
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODkxMzgyMTUsInVzZXJJZCI6IjY0YWNkZWZlYWZiMDBmOTUxNmU3NDUxNyJ9.zon79ppby-ZHHb6H0QcI3mYBDYXyUsPCv7fXlvpdXBg

###
# Get a user conversation
GET http://localhost:8080/api/users/conversations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODkxMzgyMTUsInVzZXJJZCI6IjY0YWNkZWZlYWZiMDBmOTUxNmU3NDUxNyJ9.zon79ppby-ZHHb6H0QcI3mYBDYXyUsPCv7fXlvpdXBg

###
# Create a conversation
POST http://localhost:8080/api/conversations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODkxMzgyMTUsInVzZXJJZCI6IjY0YWNkZWZlYWZiMDBmOTUxNmU3NDUxNyJ9.zon79ppby-ZHHb6H0QcI3mYBDYXyUsPCv7fXlvpdXBg

{
  "recipientId": "64ac3c0aae57ea3686a4c22w0"
}
